// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/blue22bk.tga
gfx/env/blue22dn.tga
gfx/env/blue22ft.tga
gfx/env/blue22lf.tga
gfx/env/blue22rt.tga
gfx/env/blue22up.tga
models/aomdc/items/w_deagleclip.mdl
models/aomdc/items/w_glockclip.mdl
models/aomdc/items/w_medkit.mdl
models/aomdc/items/w_mp5kclip.mdl
models/aomdc/items/w_revolverrounds.mdl
models/aomdc/misc/hornet.mdl
models/aomdc/props/2.mdl
models/aomdc/props/baenk.mdl
models/aomdc/props/bush_noleaves.mdl
models/aomdc/props/elbox.mdl
models/aomdc/props/grass1.mdl
models/aomdc/props/kontainer_bl.mdl
models/aomdc/props/kontainer_gr.mdl
models/aomdc/props/palette.mdl
models/aomdc/props/pipe_rakt_2.mdl
models/aomdc/props/shelf1.mdl
models/aomdc/props/shelf3.mdl
models/aomdc/props/soppase.mdl
models/aomdc/props/soptunna.mdl
models/aomdc/props/trash2.mdl
models/aomdc/props/trash3.mdl
models/aomdc/props/trash4.mdl
models/aomdc/props/xen_trashcan.mdl
sound/aomdc/ambience/avem-short.wav
sound/aomdc/ambience/broken_fan2.wav
sound/aomdc/ambience/crickets.wav
sound/aomdc/ambience/darkalley_river.wav
sound/aomdc/ambience/sheller.wav
sound/aomdc/ambience/sparks.wav
sound/aomdc/ambience/t_outdown.wav
sound/aomdc/ambience/wind2.wav
sound/aomdc/aompa/alienhive.wav
sound/aomdc/aompa/bigshadowsounds.wav
sound/aomdc/aompa/cagesound.wav
sound/aomdc/aompa/prisonhall.wav
sound/aomdc/buttons/button1.wav
sound/aomdc/buttons/button10.wav
sound/aomdc/buttons/button3.wav
sound/aomdc/buttons/button4.wav
sound/aomdc/buttons/button5.wav
sound/aomdc/buttons/button6.wav
sound/aomdc/buttons/button7.wav
sound/aomdc/buttons/button8.wav
sound/aomdc/buttons/button9.wav
sound/aomdc/buttons/latchlocked1.wav
sound/aomdc/buttons/latchunlocked1.wav
sound/aomdc/debris/bustflesh2.wav
sound/aomdc/debris/bustglass1.wav
sound/aomdc/debris/bustglass2.wav
sound/aomdc/debris/bustglass3.wav
sound/aomdc/debris/bustmetal1.wav
sound/aomdc/debris/bustmetal2.wav
sound/aomdc/debris/glass1.wav
sound/aomdc/debris/glass2.wav
sound/aomdc/debris/glass3.wav
sound/aomdc/debris/glass4.wav
sound/aomdc/debris/metal1.wav
sound/aomdc/debris/metal2.wav
sound/aomdc/debris/metal3.wav
sound/aomdc/debris/metal4.wav
sound/aomdc/debris/metal5.wav
sound/aomdc/debris/metal6.wav
sound/aomdc/debris/pushbox1.wav
sound/aomdc/debris/pushbox2.wav
sound/aomdc/debris/pushbox3.wav
sound/aomdc/debris/zap1.wav
sound/aomdc/debris/zap4.wav
sound/aomdc/doors/doormove1.wav
sound/aomdc/doors/doormove10.wav
sound/aomdc/doors/doormove2.wav
sound/aomdc/doors/doormove3.wav
sound/aomdc/doors/doormove4.wav
sound/aomdc/doors/doormove5.wav
sound/aomdc/doors/doormove6.wav
sound/aomdc/doors/doormove7.wav
sound/aomdc/doors/doormove8.wav
sound/aomdc/doors/doormove9.wav
sound/aomdc/items/flashlight1.wav
sound/aomdc/items/smallmedkit1.wav
sound/aomdc/items/weapondrop1.wav
sound/aomdc/monsters/face/ag_buzz1.wav
sound/aomdc/monsters/face/ag_hornethit1.wav
sound/aomdc/monsters/face/ag_hornethit2.wav
sound/aomdc/monsters/face/ag_hornethit3.wav
sound/aomdc/musics/creditnote.wav
sound/aomdc/plats/elevmove1.wav
sound/aomdc/weapons/explode3.wav
sprites/aomdc/bigspit.spr
sprites/aomdc/flashing01.spr
sprites/aomdc/laserbeam.spr
sprites/aomdc/mommaspit.spr
sprites/aomdc/mommaspout.spr
sprites/aomdc/muz1.spr
sprites/aomdc/muz4.spr
sprites/aomdc/shockwave.spr
sprites/aomdc/tinyspit.spr
sprites/aomdc/xspark4.spr
