// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomreal.wad
gfx/env/darkcitybk.tga
gfx/env/darkcitydn.tga
gfx/env/darkcityft.tga
gfx/env/darkcitylf.tga
gfx/env/darkcityrt.tga
gfx/env/darkcityup.tga
models/aomclassic/hornet.mdl
models/aomclassic/items/w_ak47clip.mdl
models/aomclassic/items/w_battery.mdl
models/aomclassic/items/w_berettaclip.mdl
models/aomclassic/items/w_deagleclip.mdl
models/aomclassic/items/w_medkit.mdl
models/aomclassic/lambda_custom.mdl
models/aomclassic/monsters/devourer/devourer.mdl
models/aomclassic/monsters/face/face.mdl
models/aomclassic/monsters/twitcher/twitcher.mdl
models/aomclassic/weapons/ak47/p_clak47.mdl
models/aomclassic/weapons/ak47/v_clak47.mdl
models/aomclassic/weapons/ak47/w_clak47.mdl
models/aomclassic/weapons/beretta/p_clberetta.mdl
models/aomclassic/weapons/beretta/v_clberetta.mdl
models/aomclassic/weapons/beretta/w_clberetta.mdl
models/aomclassic/weapons/deagle/p_cldeagle.mdl
models/aomclassic/weapons/deagle/v_cldeagle.mdl
models/aomclassic/weapons/deagle/w_cldeagle.mdl
models/aomclassic/weapons/knife/p_clknife.mdl
models/aomclassic/weapons/knife/v_clknife.mdl
models/aomclassic/weapons/knife/w_clknife.mdl
models/aomclassic/weapons/shotgun/p_clshotgun.mdl
models/aomclassic/weapons/shotgun/v_clshotgun.mdl
models/aomclassic/weapons/shotgun/w_clshotgun.mdl
sound/aomclassic/ambience/drips.wav
sound/aomclassic/ambience/sparks.wav
sound/aomclassic/aompa/sickfromsick.wav
sound/aomclassic/buttons/button5.wav
sound/aomclassic/debris/bustglass1.wav
sound/aomclassic/debris/bustglass2.wav
sound/aomclassic/debris/bustglass3.wav
sound/aomclassic/debris/glass1.wav
sound/aomclassic/debris/glass2.wav
sound/aomclassic/debris/glass3.wav
sound/aomclassic/debris/glass4.wav
sound/aomclassic/debris/zap1.wav
sound/aomclassic/debris/zap4.wav
sound/aomclassic/doors/doormove4.wav
sound/aomclassic/doors/doormove5.wav
sound/aomclassic/doors/doormove6.wav
sound/aomclassic/doors/doormove9.wav
sound/aomclassic/doors/doorstop4.wav
sound/aomclassic/fans/fan2.wav
sound/aomclassic/items/flashlight1.wav
sound/aomclassic/items/smallmedkit1.wav
sound/aomclassic/misc/checkpoint.wav
sound/aomclassic/monsters/devourer/bcl_alert2.wav
sound/aomclassic/monsters/face/ag_attack1.wav
sound/aomclassic/monsters/face/ag_attack2.wav
sound/aomclassic/monsters/face/ag_attack3.wav
sound/aomclassic/monsters/face/ag_buzz1.wav
sound/aomclassic/monsters/face/ag_die1.wav
sound/aomclassic/monsters/face/ag_die2.wav
sound/aomclassic/monsters/face/ag_die3.wav
sound/aomclassic/monsters/face/ag_die4.wav
sound/aomclassic/monsters/face/ag_die5.wav
sound/aomclassic/monsters/face/ag_hornethit1.wav
sound/aomclassic/monsters/face/ag_hornethit2.wav
sound/aomclassic/monsters/face/ag_hornethit3.wav
sound/aomclassic/monsters/face/ag_pain1.wav
sound/aomclassic/monsters/face/ag_pain2.wav
sound/aomclassic/monsters/face/ag_pain3.wav
sound/aomclassic/monsters/face/ag_pain4.wav
sound/aomclassic/monsters/face/ag_pain5.wav
sound/aomclassic/monsters/twitcher/zo_alert10.wav
sound/aomclassic/monsters/twitcher/zo_alert20.wav
sound/aomclassic/monsters/twitcher/zo_alert30.wav
sound/aomclassic/monsters/twitcher/zo_attack1.wav
sound/aomclassic/monsters/twitcher/zo_attack2.wav
sound/aomclassic/monsters/twitcher/zo_pain1.wav
sound/aomclassic/monsters/twitcher/zo_pain2.wav
sound/aomclassic/plats/elevmove1.wav
sound/aomclassic/weapons/ak47/ak47_boltpull.wav
sound/aomclassic/weapons/ak47/ak47_clipin.wav
sound/aomclassic/weapons/ak47/ak47_clipout.wav
sound/aomclassic/weapons/ak47/ak47_fire.wav
sound/aomclassic/weapons/ak47/ak47_stockup.wav
sound/aomclassic/weapons/beretta/beretta_clipin.wav
sound/aomclassic/weapons/beretta/beretta_clipout.wav
sound/aomclassic/weapons/beretta/beretta_fire.wav
sound/aomclassic/weapons/beretta/beretta_reload.wav
sound/aomclassic/weapons/beretta/beretta_slide.wav
sound/aomclassic/weapons/deagle/deagle_draw.wav
sound/aomclassic/weapons/deagle/deagle_fire.wav
sound/aomclassic/weapons/deagle/deagle_reload.wav
sound/aomclassic/weapons/deagle/deagle_slide.wav
sound/aomclassic/weapons/explode1.wav
sound/aomclassic/weapons/knife/knife_hit1.wav
sound/aomclassic/weapons/knife/knife_hit2.wav
sound/aomclassic/weapons/knife/knife_hitbod1.wav
sound/aomclassic/weapons/knife/knife_hitbod2.wav
sound/aomclassic/weapons/knife/knife_hitbod3.wav
sound/aomclassic/weapons/knife/knife_miss1.wav
sound/aomclassic/weapons/shotgun/scock1.wav
sound/aomclassic/weapons/shotgun/shotgun_draw.wav
sound/aomclassic/weapons/shotgun/shotgun_fire.wav
sound/aomclassic/weapons/shotgun/shotgun_holster.wav
sound/aomclassic/weapons/shotgun/shotgun_pump.wav
sound/aomdc/misc/checkpoint.wav
sound/weapons/dryfire.wav
sprites/aomclassic/bigspit.spr
sprites/aomclassic/blood.spr
sprites/aomclassic/clak47.spr
sprites/aomclassic/clberetta.spr
sprites/aomclassic/cldeagle.spr
sprites/aomclassic/clknife.spr
sprites/aomclassic/clshotgun.spr
sprites/aomclassic/fog5.spr
sprites/aomclassic/keyicon.spr
sprites/aomclassic/laserbeam.spr
sprites/aomclassic/levelchange.spr
sprites/aomclassic/mommaspit.spr
sprites/aomclassic/mommaspout.spr
sprites/aomclassic/moths.spr
sprites/aomclassic/muz1.spr
sprites/aomclassic/muz4.spr
sprites/aomclassic/muz8.spr
sprites/aomclassic/shockwave.spr
sprites/aomclassic/tinyspit.spr
sprites/aomclassic/weapon_clak47.txt
sprites/aomclassic/weapon_clberetta.txt
sprites/aomclassic/weapon_cldeagle.txt
sprites/aomclassic/weapon_clknife.txt
sprites/aomclassic/weapon_clshotgun.txt
sprites/aomclassic/xspark4.spr
