// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/sorgardbk.tga
gfx/env/sorgarddn.tga
gfx/env/sorgardft.tga
gfx/env/sorgardlf.tga
gfx/env/sorgardrt.tga
gfx/env/sorgardup.tga
models/aomdc/items/w_battery.mdl
models/aomdc/items/w_deagleclip.mdl
models/aomdc/items/w_glockclip.mdl
models/aomdc/items/w_medkit.mdl
models/aomdc/items/w_mp5kclip.mdl
models/aomdc/items/w_revolverrounds.mdl
models/aomdc/lambda_custom.mdl
models/aomdc/misc/hornet.mdl
models/aomdc/monsters/ghost/ghost.mdl
models/aomdc/monsters/handcrab/handcrab.mdl
models/aomdc/monsters/hellhound/hellhound.mdl
models/aomdc/monsters/spitter/spitter.mdl
models/aomdc/monsters/twitcher/twitcher.mdl
models/aomdc/props/farmor.mdl
models/aomdc/props/fork.mdl
models/aomdc/props/matsalsstol.mdl
models/aomdc/props/phonebooth1.mdl
models/aomdc/props/shelf3.mdl
models/aomdc/props/shelf4.mdl
models/aomdc/props/ventilation.mdl
models/aomdc/weapons/axe/p_dcaxe.mdl
models/aomdc/weapons/axe/v_dcaxe.mdl
models/aomdc/weapons/axe/w_dcaxe.mdl
models/aomdc/weapons/beretta/p_dcberetta.mdl
models/aomdc/weapons/beretta/v_dcberetta.mdl
models/aomdc/weapons/beretta/w_dcberetta.mdl
models/aomdc/weapons/deagle/p_dcdeagle.mdl
models/aomdc/weapons/deagle/v_dcdeagle.mdl
models/aomdc/weapons/deagle/w_dcdeagle.mdl
models/aomdc/weapons/glock/p_dcglock.mdl
models/aomdc/weapons/glock/v_dcglock.mdl
models/aomdc/weapons/glock/w_dcglock.mdl
models/aomdc/weapons/hammer/p_dchammer.mdl
models/aomdc/weapons/hammer/v_dchammer.mdl
models/aomdc/weapons/hammer/w_dchammer.mdl
models/aomdc/weapons/knife/p_dcknife.mdl
models/aomdc/weapons/knife/v_dcknife.mdl
models/aomdc/weapons/knife/w_dcknife.mdl
models/aomdc/weapons/l85a1/p_dcl85a1.mdl
models/aomdc/weapons/l85a1/v_dcl85a1.mdl
models/aomdc/weapons/l85a1/w_dcl85a1.mdl
models/aomdc/weapons/mp5k/p_dcmp5k.mdl
models/aomdc/weapons/mp5k/v_dcmp5k.mdl
models/aomdc/weapons/mp5k/w_dcmp5k.mdl
models/aomdc/weapons/p228/p_dcp228.mdl
models/aomdc/weapons/p228/v_dcp228.mdl
models/aomdc/weapons/p228/w_dcp228.mdl
models/aomdc/weapons/revolver/p_dcrevolver.mdl
models/aomdc/weapons/revolver/v_dcrevolver.mdl
models/aomdc/weapons/revolver/w_dcrevolver.mdl
models/aomdc/weapons/shotgun/p_dcshotgun.mdl
models/aomdc/weapons/shotgun/v_dcshotgun.mdl
models/aomdc/weapons/shotgun/w_dcshotgun.mdl
models/aomdc/weapons/uzi/p_dcuzi.mdl
models/aomdc/weapons/uzi/v_dcuzi.mdl
models/aomdc/weapons/uzi/w_dcuzi.mdl
sound/aomdc/ambience/high_wind.wav
sound/aomdc/ambience/sparks.wav
sound/aomdc/aompa/r_hosp2.wav
sound/aomdc/buttons/button1.wav
sound/aomdc/buttons/button10.wav
sound/aomdc/buttons/button3.wav
sound/aomdc/buttons/button4.wav
sound/aomdc/buttons/button5.wav
sound/aomdc/buttons/button6.wav
sound/aomdc/buttons/button7.wav
sound/aomdc/buttons/button8.wav
sound/aomdc/buttons/button9.wav
sound/aomdc/buttons/latchlocked1.wav
sound/aomdc/buttons/latchunlocked1.wav
sound/aomdc/debris/bustflesh2.wav
sound/aomdc/debris/bustglass1.wav
sound/aomdc/debris/bustglass2.wav
sound/aomdc/debris/bustglass3.wav
sound/aomdc/debris/bustmetal1.wav
sound/aomdc/debris/bustmetal2.wav
sound/aomdc/debris/glass1.wav
sound/aomdc/debris/glass2.wav
sound/aomdc/debris/glass3.wav
sound/aomdc/debris/glass4.wav
sound/aomdc/debris/metal1.wav
sound/aomdc/debris/metal2.wav
sound/aomdc/debris/metal3.wav
sound/aomdc/debris/metal4.wav
sound/aomdc/debris/metal5.wav
sound/aomdc/debris/metal6.wav
sound/aomdc/debris/pushbox1.wav
sound/aomdc/debris/pushbox2.wav
sound/aomdc/debris/pushbox3.wav
sound/aomdc/debris/zap1.wav
sound/aomdc/debris/zap4.wav
sound/aomdc/doors/doormove1.wav
sound/aomdc/doors/doormove10.wav
sound/aomdc/doors/doormove2.wav
sound/aomdc/doors/doormove3.wav
sound/aomdc/doors/doormove4.wav
sound/aomdc/doors/doormove5.wav
sound/aomdc/doors/doormove6.wav
sound/aomdc/doors/doormove7.wav
sound/aomdc/doors/doormove8.wav
sound/aomdc/doors/doormove9.wav
sound/aomdc/fans/fan1.wav
sound/aomdc/fans/fan2.wav
sound/aomdc/fans/fan3.wav
sound/aomdc/items/flashlight1.wav
sound/aomdc/items/smallmedkit1.wav
sound/aomdc/items/weapondrop1.wav
sound/aomdc/misc/checkpoint.wav
sound/aomdc/monsters/face/ag_buzz1.wav
sound/aomdc/monsters/face/ag_hornethit1.wav
sound/aomdc/monsters/face/ag_hornethit2.wav
sound/aomdc/monsters/face/ag_hornethit3.wav
sound/aomdc/monsters/ghost/ear_ringing.wav
sound/aomdc/monsters/ghost/slv_alert2.wav
sound/aomdc/monsters/ghost/slv_die.wav
sound/aomdc/monsters/ghost/slv_word3.wav
sound/aomdc/monsters/ghost/slv_word4.wav
sound/aomdc/monsters/ghost/slv_word5.wav
sound/aomdc/monsters/ghost/slv_word7.wav
sound/aomdc/monsters/handcrab/hc_alert1.wav
sound/aomdc/monsters/handcrab/hc_alert2.wav
sound/aomdc/monsters/handcrab/hc_attack1.wav
sound/aomdc/monsters/handcrab/hc_attack2.wav
sound/aomdc/monsters/handcrab/hc_attack3.wav
sound/aomdc/monsters/handcrab/hc_die1.wav
sound/aomdc/monsters/handcrab/hc_die2.wav
sound/aomdc/monsters/handcrab/hc_headbite.wav
sound/aomdc/monsters/handcrab/hc_idle1.wav
sound/aomdc/monsters/handcrab/hc_pain1.wav
sound/aomdc/monsters/handcrab/hc_pain2.wav
sound/aomdc/monsters/handcrab/hc_pain3.wav
sound/aomdc/monsters/hellhound/he_alert1.wav
sound/aomdc/monsters/hellhound/he_alert2.wav
sound/aomdc/monsters/hellhound/he_blast1.wav
sound/aomdc/monsters/hellhound/he_blast2.wav
sound/aomdc/monsters/hellhound/he_blast3.wav
sound/aomdc/monsters/hellhound/he_die1.wav
sound/aomdc/monsters/hellhound/he_die2.wav
sound/aomdc/monsters/hellhound/he_die3.wav
sound/aomdc/monsters/hellhound/he_pain1.wav
sound/aomdc/monsters/hellhound/he_pain2.wav
sound/aomdc/monsters/spitter/bc_acid1.wav
sound/aomdc/monsters/spitter/bc_attack1.wav
sound/aomdc/monsters/spitter/bc_attack2.wav
sound/aomdc/monsters/spitter/bc_attackgrowl.wav
sound/aomdc/monsters/spitter/bc_attackgrowl2.wav
sound/aomdc/monsters/spitter/bc_attackgrowl3.wav
sound/aomdc/monsters/spitter/bc_bite1.wav
sound/aomdc/monsters/spitter/bc_bite2.wav
sound/aomdc/monsters/spitter/bc_bite3.wav
sound/aomdc/monsters/spitter/bc_die1.wav
sound/aomdc/monsters/spitter/bc_die2.wav
sound/aomdc/monsters/spitter/bc_die3.wav
sound/aomdc/monsters/spitter/bc_idle1.wav
sound/aomdc/monsters/spitter/bc_pain1.wav
sound/aomdc/monsters/spitter/bc_pain2.wav
sound/aomdc/monsters/spitter/bc_pain3.wav
sound/aomdc/monsters/spitter/bc_pain4.wav
sound/aomdc/monsters/spitter/bc_spithit1.wav
sound/aomdc/monsters/twitcher1/claw_miss1.wav
sound/aomdc/monsters/twitcher1/claw_miss2.wav
sound/aomdc/monsters/twitcher1/claw_strike1.wav
sound/aomdc/monsters/twitcher1/claw_strike2.wav
sound/aomdc/monsters/twitcher1/claw_strike3.wav
sound/aomdc/monsters/twitcher1/zo_alert10.wav
sound/aomdc/monsters/twitcher1/zo_alert20.wav
sound/aomdc/monsters/twitcher1/zo_alert30.wav
sound/aomdc/monsters/twitcher1/zo_attack1.wav
sound/aomdc/monsters/twitcher1/zo_attack2.wav
sound/aomdc/monsters/twitcher1/zo_idle1.wav
sound/aomdc/monsters/twitcher1/zo_pain1.wav
sound/aomdc/monsters/twitcher1/zo_pain2.wav
sound/aomdc/plats/elevmove1.wav
sound/aomdc/weapons/axe/axe_hit.wav
sound/aomdc/weapons/axe/axe_hitbody.wav
sound/aomdc/weapons/axe/axe_swing.wav
sound/aomdc/weapons/beretta/beretta_fire.wav
sound/aomdc/weapons/beretta/beretta_magin.wav
sound/aomdc/weapons/beretta/beretta_magout.wav
sound/aomdc/weapons/beretta/beretta_magplace.wav
sound/aomdc/weapons/beretta/beretta_slideforward.wav
sound/aomdc/weapons/deagle/deagle_clipin.wav
sound/aomdc/weapons/deagle/deagle_clipout.wav
sound/aomdc/weapons/deagle/deagle_fire.wav
sound/aomdc/weapons/deagle/deagle_slide.wav
sound/aomdc/weapons/explode3.wav
sound/aomdc/weapons/glock/glock_fire.wav
sound/aomdc/weapons/glock/glock_magin.wav
sound/aomdc/weapons/glock/glock_magout.wav
sound/aomdc/weapons/glock/glock_magplace.wav
sound/aomdc/weapons/glock/glock_slideforward.wav
sound/aomdc/weapons/hammer/hammer_hit.wav
sound/aomdc/weapons/hammer/hammer_hitbody.wav
sound/aomdc/weapons/hammer/hammer_miss.wav
sound/aomdc/weapons/knife/knife_hit1.wav
sound/aomdc/weapons/knife/knife_hit2.wav
sound/aomdc/weapons/knife/knife_swing1.wav
sound/aomdc/weapons/knife/knife_wall1.wav
sound/aomdc/weapons/knife/knife_wall2.wav
sound/aomdc/weapons/l85a1/l85a1_fire.wav
sound/aomdc/weapons/mp5k/mp5k_boltback.wav
sound/aomdc/weapons/mp5k/mp5k_boltforward.wav
sound/aomdc/weapons/mp5k/mp5k_fire.wav
sound/aomdc/weapons/mp5k/mp5k_magin.wav
sound/aomdc/weapons/mp5k/mp5k_magout.wav
sound/aomdc/weapons/p228/p228_fire.wav
sound/aomdc/weapons/p228/p228_magin.wav
sound/aomdc/weapons/p228/p228_magout.wav
sound/aomdc/weapons/p228/p228_magplace.wav
sound/aomdc/weapons/p228/p228_slideforward.wav
sound/aomdc/weapons/revolver/revolver_draw.wav
sound/aomdc/weapons/revolver/revolver_fire.wav
sound/aomdc/weapons/revolver/revolver_reload.wav
sound/aomdc/weapons/shotgun/shotgun_fire.wav
sound/aomdc/weapons/shotgun/shotgun_insert.wav
sound/aomdc/weapons/shotgun/shotgun_pump.wav
sound/aomdc/weapons/shotgun/sshell1.wav
sound/aomdc/weapons/shotgun/sshell2.wav
sound/aomdc/weapons/shotgun/sshell3.wav
sound/aomdc/weapons/uzi/uzi_boltpull.wav
sound/aomdc/weapons/uzi/uzi_fire.wav
sound/aomdc/weapons/uzi/uzi_magin.wav
sound/aomdc/weapons/uzi/uzi_magout.wav
sound/blackdog/dog_run.wav
sound/weapons/dryfire.wav
sprites/aomdc/bigspit.spr
sprites/aomdc/dcaxe.spr
sprites/aomdc/dcberetta.spr
sprites/aomdc/dcdeagle.spr
sprites/aomdc/dcglock.spr
sprites/aomdc/dchammer.spr
sprites/aomdc/dcknife.spr
sprites/aomdc/dcl85a1.spr
sprites/aomdc/dcmp5k.spr
sprites/aomdc/dcp228.spr
sprites/aomdc/dcrevolver.spr
sprites/aomdc/dcshotgun.spr
sprites/aomdc/dcuzi.spr
sprites/aomdc/keyicon.spr
sprites/aomdc/laserbeam.spr
sprites/aomdc/mommaspit.spr
sprites/aomdc/mommaspout.spr
sprites/aomdc/muz1.spr
sprites/aomdc/muz4.spr
sprites/aomdc/ropeicon.spr
sprites/aomdc/shockwave.spr
sprites/aomdc/tinyspit.spr
sprites/aomdc/weapon_dcaxe.txt
sprites/aomdc/weapon_dcberetta.txt
sprites/aomdc/weapon_dcdeagle.txt
sprites/aomdc/weapon_dcglock.txt
sprites/aomdc/weapon_dchammer.txt
sprites/aomdc/weapon_dcknife.txt
sprites/aomdc/weapon_dcl85a1.txt
sprites/aomdc/weapon_dcmp5k.txt
sprites/aomdc/weapon_dcp228.txt
sprites/aomdc/weapon_dcrevolver.txt
sprites/aomdc/weapon_dcshotgun.txt
sprites/aomdc/weapon_dcuzi.txt
sprites/aomdc/xspark4.spr
sprites/aomdc/z_checkpoint.spr
sprites/aomdc/z_levelchange.spr
