eshq.wad
gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/eshq/enemi/zombie.mdl
models/eshq/objects/bath.mdl
models/eshq/objects/bed.mdl
models/eshq/objects/bigspiggot.mdl
models/eshq/objects/bookgibs.mdl
models/eshq/objects/kitchensink.mdl
models/eshq/objects/simplecar.mdl
models/eshq/objects/simplefork.mdl
models/eshq/objects/simplejeep.mdl
models/eshq/objects/simplepolice.mdl
models/eshq/objects/simplevan.mdl
models/eshq/objects/toilet.mdl
models/eshq/objects/tree1.mdl
models/eshq/objects/tree2.mdl