eshq.wad
gfx/env/eshq_firmor_bk.tga
gfx/env/eshq_firmor_dn.tga
gfx/env/eshq_firmor_ft.tga
gfx/env/eshq_firmor_lf.tga
gfx/env/eshq_firmor_rt.tga
gfx/env/eshq_firmor_up.tga
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/eshq/enemi/zombie.mdl
models/eshq/objects/bath.mdl
models/eshq/objects/bed.mdl
models/eshq/objects/bigspiggot.mdl
models/eshq/objects/bookgibs.mdl
models/eshq/objects/kitchensink.mdl
models/eshq/objects/simplecar.mdl
models/eshq/objects/simplefork.mdl
models/eshq/objects/simplejeep.mdl
models/eshq/objects/simplepolice.mdl
models/eshq/objects/simplevan.mdl
models/eshq/objects/toilet.mdl
models/eshq/objects/tree1.mdl
models/eshq/objects/tree2.mdl