hopelessness2.wad
sound/ambience/alien_teleport.wav
sound/ambience/steam_big2.wav
sound/ambience/steam_sml2.wav
sound/garg/_period.wav
sound/items/crystal_pickup.wav
sound/music/suspence5.wav
sound/voice/agony.wav
sprites/antirush/percent.spr