hopelessness2.wad
models/nohope/key2.mdl
models/nohope/w_hook.mdl
models/nohope/w_hookt.mdl
models/nohope/w_pliers.mdl
models/nohope/w_screwdriver.mdl
models/nohope/w_wires.mdl
sound/ambience/alien_teleport.wav
sound/ambience/earthquake.wav
sound/debris/impact.wav
sound/garg/_period.wav
sound/items/hook_pickup.wav
sound/items/key_pickup.wav
sound/items/key_use.wav
sound/items/pliers_pickup.wav
sound/items/screwdriver_pickup.wav
sound/items/wires_pickup.wav
sound/music/suspence3.wav
sound/voice/agony.wav
sound/voice/crying.wav
sprites/antirush/percent.spr