sprites/hl_weapons/weapon_hl357.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
gfx/env/hackbk.tga
gfx/env/hackdn.tga
gfx/env/hackft.tga
gfx/env/hacklf.tga
gfx/env/hackrt.tga
gfx/env/hackup.tga