decals.wad
gfx/env/dfcliffbk.bmp
gfx/env/dfcliffbk.tga
gfx/env/dfcliffdn.bmp
gfx/env/dfcliffdn.tga
gfx/env/dfcliffft.bmp
gfx/env/dfcliffft.tga
gfx/env/dfclifflf.bmp
gfx/env/dfclifflf.tga
gfx/env/dfcliffrt.bmp
gfx/env/dfcliffrt.tga
gfx/env/dfcliffup.bmp
gfx/env/dfcliffup.tga
halflife.wad
liquids.wad
maps/polar_rescue.cfg
maps/polar_rescue.gmr
maps/polar_rescue.gsr
maps/polar_rescue.res
maps/polar_rescue_materials.txt
maps/polar_rescue_motd.txt
maps/polar_rescue_skl.cfg
models/adamr/backpack_sven.mdl
models/adamr/ceiling_lamp.mdl
models/adamr/key.mdl
models/adamr/keycard_l1.mdl
models/adamr/keycard_l2.mdl
models/adamr/keycard_l3.mdl
models/adamr/toolbox.mdl
models/adamr/weapons/gold357/p_gold357.mdl
models/adamr/weapons/gold357/v_gold357.mdl
models/adamr/weapons/gold357/v_gold357_op4.mdl
models/adamr/weapons/gold357/w_gold357.mdl
models/blkop_apache.mdl
models/blkop_apacheT.mdl
models/ginsmodels/gins_deskchair.mdl
models/ginsmodels/gins_substation.mdl
models/ginsmodels/gins_trashcan.mdl
models/ginsmodels/lag_radio.mdl
models/greysnake/hgrunt_opfor.mdl
models/greysnake/massn.mdl
models/hezus/mt32.mdl
models/osprey.mdl
models/ospreyT.mdl
models/player/helmet/helmet.mdl
models/revil/Furnature/sink.mdl
models/revil/Furnature/toilet.mdl
models/the303/domecam.mdl
nw.wad
sound/adamr/bigexplode.wav
sound/adamr/blipblipblip.wav
sound/adamr/electricbuzz.wav
sound/adamr/hgrunt/call_backup.wav
sound/adamr/lava.wav
sound/adamr/music/lotus-tuc-fmopl-cd1.ogg
sound/adamr/music/lotus-tuc-fmopl-cd2.ogg
sound/adamr/music/lotus-tuc-fmopl-cd3.ogg
sound/adamr/music/lotus-tuc-fmopl-cd4.ogg
sound/adamr/music/lotus-tuc-fmopl-cd5.ogg
sound/adamr/music/lotus-tuc-fmopl-cd6.ogg
sound/adamr/music/lotus-tuc-mt32-cd1.ogg
sound/adamr/music/lotus-tuc-mt32-cd2.ogg
sound/adamr/music/lotus-tuc-mt32-cd3.ogg
sound/adamr/music/lotus-tuc-mt32-cd4.ogg
sound/adamr/music/lotus-tuc-mt32-cd5.ogg
sound/adamr/music/lotus-tuc-mt32-cd6.ogg
sound/adamr/polar_rescue/10_minutes_remaining.wav
sound/adamr/polar_rescue/15_minutes_remaining.wav
sound/adamr/polar_rescue/20_minutes_remaining.wav
sound/adamr/polar_rescue/3_minutes_remaining.wav
sound/adamr/polar_rescue/5_minutes_remaining.wav
sound/adamr/polar_rescue/60_seconds_remaining.wav
sound/adamr/polar_rescue/missileroom_door_first_speech.wav
sound/adamr/polar_rescue/vault_door_first_speech.wav
scripts/maps/polar_rescue.as
sprites/adamr/adambean.spr
sprites/adamr/diff.spr
sprites/adamr/diff_easy.spr
sprites/adamr/diff_extreme.spr
sprites/adamr/diff_hard.spr
sprites/adamr/diff_normal.spr
sprites/adamr/map_polarrescue.spr
sprites/adamr/pointers/pointer-blast.spr
sprites/adamr/pointers/pointer-collect.spr
sprites/adamr/pointers/pointer-destroy.spr
sprites/adamr/pointers/pointer-kill.spr
sprites/adamr/pointers/pointer-objective.spr
sprites/adamr/pointers/pointer-protect.spr
sprites/adamr/pointers/pointer-reach.spr
sprites/adamr/pointers/pointer-use.spr
submerged.wad
submerged_addons.wad
xeno.wad
