maps/evasion3_v3.bsp
maps/evasion4_v3.bsp
models/cubemath/chars/d0.mdl
models/cubemath/chars/d5.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/cubemath/key.mdl
models/cubemath/padlock.mdl
models/cubemath/skull.mdl
sound/evasion/fan4_new.wav
sound/evasion/inLNpipes.wav
sound/evasion/LNpipes1.wav
sound/evasion/scaryN5.wav
sound/evasion/scream6.wav
sound/evasion/of7a0_gm04_short.ogg
sound/evasion/shephard_intro.wav
sound/evasion/music/evasion3.mp3
sound/evasion/music/evasion4.mp3
sound/evasion/music/evasion5.mp3
sound/evasion/music/evasion6.mp3