hopelessness2.wad
models/nohope/guest.mdl
models/nohope/sci_head.mdl
models/nohope/w_security.mdl
models/nohope/w_securityt.mdl
sound/ambience/alien_teleport.wav
sound/ambience/electric_damage.wav
sound/ambience/steam_big2.wav
sound/garg/_period.wav
sound/items/head_pickup.wav
sound/items/keycard_pickup.wav
sound/items/valve_pickup.wav
sound/music/horror2.wav
sound/voice/agony.wav
sprites/antirush/percent.spr