hopelessness.wad
models/nohope/gus.mdl
models/nohope/gus01.mdl
models/nohope/gus02.mdl
models/nohope/gus03.mdl
models/nohope/gus04.mdl
models/nohope/gus05.mdl
models/nohope/gus06.mdl
models/nohope/gus07.mdl
models/nohope/gust.mdl
models/nohope/key1.mdl
sound/ambience/alien_teleport.wav
sound/ambience/impact_crete.wav
sound/garg/_period.wav
sound/music/calmness3.wav
sound/music/eff2.wav
sprites/antirush/percent.spr
