hopelessness2.wad
models/nohope/dead_barney.mdl
models/nohope/dead_barney01.mdl
models/nohope/guest.mdl
sound/ambience/metal1.wav
sound/ambience/steam_big2.wav
sound/ambience/tunnel_amb.wav
sound/garg/_period.wav
sound/music/calmness3.wav
sound/music/chapter_texteff.wav
sound/music/intro.wav
sound/voice/agony.wav
sound/voice/sc_intro.wav
sound/voice/scream1.wav
sound/voice/scream2.wav
sprites/antirush/percent.spr