hopelessness.wad
models/nohope/dead_barney.mdl
models/nohope/dead_barney01.mdl
models/nohope/gus.mdl
models/nohope/gus01.mdl
models/nohope/gus02.mdl
models/nohope/gus03.mdl
models/nohope/gus04.mdl
models/nohope/gus05.mdl
models/nohope/gus06.mdl
models/nohope/gus07.mdl
models/nohope/gust.mdl
models/nohope/otis.mdl
models/nohope/otis01.mdl
models/nohope/otis02.mdl
models/nohope/otis03.mdl
sound/ambience/alien_teleport.wav
sound/ambience/metal1.wav
sound/garg/_period.wav
sound/music/calmness2.wav
sound/music/eff1.wav
sound/music/suspence2.wav
sprites/antirush/percent.spr